# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gKrBIcqLiXcX378QHojBKNjiea74f96D
"""

# create class passenger

class Passenger:
  #constructor of class passenger
    def __init__(self, passenger_id, passenger_name, booking_id, flight_number):
        # Initialize Passenger object with attributes
        self.passenger_id = passenger_id
        self.passenger_name = passenger_name
        self.booking_id = booking_id
        self.flight_number = flight_number

    # Getter methods to get values of the attributes
    def get_passenger_id(self):
        return self.passenger_id

    def get_passenger_name(self):
        return self.passenger_name

    def get_booking_id(self):
        return self.booking_id

    def get_flight_number(self):
        return self.flight_number


  # create class BoardingPassSystem
class BoardingPassSystem:


    #function to generate boarding pass
    def generate_boarding_pass(self, passenger):
        pass
 # function to retrieve boarding pass
    def retrieve_boarding_pass(self, passenger_id):
        pass

class BoardingPass:
  #constructor of BoardingPass class
    def __init__(self, boarding_pass_id, passenger_name, flight_number, departure_airport, destination_airport,
                 departure_date_time, arrival_date_time, boarding_time, seat_number, gate_number, terminal_number,
                 electronic_ticket):
              # Initialize BoardingPass object with provided attributes
        self.boarding_pass_id = boarding_pass_id
        self.passenger_name = passenger_name
        self.flight_number = flight_number
        self.departure_airport = departure_airport
        self.destination_airport = destination_airport
        self.departure_date_time = departure_date_time
        self.arrival_date_time = arrival_date_time
        self.boarding_time = boarding_time
        self.seat_number = seat_number
        self.gate_number = gate_number
        self.terminal_number = terminal_number
        self.electronic_ticket = electronic_ticket

    # Getter methods to get attribute values
    def get_boarding_pass_id(self):
        return self.boarding_pass_id

    def get_passenger_name(self):
        return self.passenger_name

    def get_flight_number(self):
        return self.flight_number

    def get_departure_airport(self):
        return self.departure_airport

    def get_destination_airport(self):
        return self.destination_airport

    def display_boarding_pass_details(self):
        return self.display_boarding_pass_details

    #  function to retrieve flight details
    def get_flight_details(self):
        pass
    # function to retrieve passenger details
    def get_passenger_details(self):
        pass

# create class Flight
class Flight:
  # constructor of class flight to intialize value to objects
    def __init__(self, flight_number, departure_airport, destination_airport, departure_datetime, arrival_datetime):
        # Initialize Flight object with given attributes
        self.flight_number = flight_number
        self.departure_airport = departure_airport
        self.destination_airport = destination_airport
        self.departure_datetime = departure_datetime
        self.arrival_datetime = arrival_datetime

    # Getter methods to get attribute values
    def get_flight_number(self):
        return self.flight_number

    def get_departure_airport(self):
        return self.departure_airport

    def get_destination_airport(self):
        return self.destination_airport

    def get_departure_datetime(self):
        return self.departure_datetime

    def get_arrival_datetime(self):
        return self.arrival_datetime

class BoardingPass:
    def __init__(self, boarding_pass_id, passenger_name, flight_number, departure_airport, destination_airport,
                 departure_date_time, arrival_date_time, boarding_time, seat_number, gate_number, terminal_number,
                 electronic_ticket):
        # Initialize BoardingPass attributes
        self.boarding_pass_id = boarding_pass_id
        self.passenger_name = passenger_name
        self.flight_number = flight_number
        self.departure_airport = departure_airport
        self.destination_airport = destination_airport
        self.departure_date_time = departure_date_time
        self.arrival_date_time = arrival_date_time
        self.boarding_time = boarding_time
        self.seat_number = seat_number
        self.gate_number = gate_number
        self.terminal_number = terminal_number
        self.electronic_ticket = electronic_ticket

    # function to display boarding pass details
    def display_boarding_pass_details(self):
        # Print boarding pass details in a formatted manner
        print(" BOARDING PASS ".center(50, "="))
        print(f"Passenger Name: {self.passenger_name}")
        print(f"Flight Number: {self.flight_number}")
        print(f"Departure Airport: {self.departure_airport}")
        print(f"Destination Airport: {self.destination_airport}")
        print(f"Departure Date and Time: {self.departure_date_time}")
        print(f"Arrival Date and Time: {self.arrival_date_time}")
        print(f"Boarding Time: {self.boarding_time}")
        print(f"Seat Number: {self.seat_number}")
        print(f"Gate Number: {self.gate_number}")
        print(f"Terminal Number: {self.terminal_number}")
        print(f"Electronic Ticket: {self.electronic_ticket}")
        print("=" * 50)



# Create a BoardingPass object to give values to the attributes
boarding_pass = BoardingPass("BP123456789", "Hasan", "ABC123", "DXB", "LAX",
                             "2024-03-01 08:00:00", "2024-03-01 11:00:00", "2024-03-01 07:30:00",
                             "25A", "C5", "Terminal 1", "ET789456123")

# Display boarding pass details
boarding_pass.display_boarding_pass_details()